version: "{build}"

pull_requests:
  do_not_increment_build_number: true
  
branches:
  only:
  - main

shallow_clone: true

image: Visual Studio 2019

build_script:
  - cmd: nuget restore
  - cmd: msbuild /p:Configuration=Debug /p:Platform="Any CPU"

test: off

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'
  - '%LocalAppData%\NuGet\v3-cache'

artifacts:
  - path: 'Skyclient-Installer-Windows\bin\Release\*.exe'
